# It is recommended that the file prefix ends in a . (dot)
file_prefix: stiubhart.
php_sock: /run/php/php7.0-fpm.sock

root:
    web: /var/www/
    sites-enabled: /etc/nginx/sites-enabled/
    sites-available: /etc/nginx/sites-available/
